=== Nevvulo/blog/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "slug": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "image": {
        "type": "string"
      },
      "createdAt": {
        "type": "integer"
      },
      "labels": {
        "type": "array"
      },
      "location": {
        "type": "string"
      },
      "difficulty": {
        "type": "string"
      },
      "reviewedBy": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "keyIdeas": {
        "type": "array"
      },
      "coverAuthor": {
        "type": "string"
      },
      "coverAuthorUrl": {
        "type": "string"
      },
      "readTimeMins": {
        "type": "integer"
      }
    },
    "required": [
      "slug",
      "title",
      "description",
      "image",
      "location",
      "createdAt"
    ]
  }
}

=== Nevvulo/blog/blogmap.json
[
	{
		"slug": "avoid-indentation-hell-with-early-returns",
		"title": "Avoid indentation hell with early returns",
		"description": "There's a better way to structure your conditional logic",
		"image": "https://i.imgur.com/BtjZedW.jpg",
		"createdAt": 1629207399000,
		"location": "posts/avoid-indentation-hell-with-early-returns.mdx",
		"labels": [
			"programming",
			"typescript",
			"code-quality"
		]
	},
	{
		"slug": "numbers-in-javascript",
		"title": "Numbers in JavaScript; harder than you think",
		"description": "Simple, innocuous methods which will trip you up when working with numbers in JavaScript",
		"image": "https://i.imgur.com/nWbP3i9.jpeg",
		"createdAt": 1627826463000,
		"labels": [
			"programming",
			"javascript"
		],
		"location": "posts/numbers-in-javascript.mdx"
	}
]
